# Generated by Django 6.0.4 on 2026-04-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pricing_type',
            field=models.CharField(choices=[('daily', 'Daily Rate'), ('monthly', 'Monthly Rate')], default='daily', max_length=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='daily_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per night', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per month', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='price_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('both', 'Both')], default='both', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_guests',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.CharField(choices=[('cebu_city', 'Cebu City'), ('lapulapu', 'Lapu-Lapu City'), ('mandaue', 'Mandaue City'), ('talisay', 'Talisay City')], max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='max_occupants',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price per night for daily rental, or monthly rate for monthly rental', max_digits=10),
        ),
    ]
