# Generated by Django 6.0.4 on 2026-04-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_booking_pricing_type_listing_daily_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='pricing_type',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='daily_price',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='monthly_price',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='price_type',
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_guests',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.CharField(choices=[('cebu_city', 'Cebu City'), ('lapulapu', 'Lapu-Lapu City')], max_length=20),
        ),
        migrations.AlterField(
            model_name='listing',
            name='max_occupants',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
