# Generated by Django 6.0.4 on 2026-04-16 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
