# Generated by Django 6.0.4 on 2026-04-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='price',
        ),
        migrations.AddField(
            model_name='listing',
            name='daily_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='location',
            field=models.CharField(choices=[('cebu_city', 'Cebu City'), ('lapulapu', 'Lapu-Lapu City'), ('mandaue', 'Mandaue City'), ('talisay', 'Talisay City'), ('naga', 'Naga City'), ('carcar', 'Carcar City'), ('toledo', 'Toledo City')], max_length=20),
        ),
    ]
