# Generated by Django 6.0.4 on 2026-04-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_alter_listing_latitude_alter_listing_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
