# Generated by Django 6.0.4 on 2026-04-17 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0009_alter_listing_latitude_alter_listing_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='longitude',
        ),
    ]
