# Generated by Django 6.0.4 on 2026-04-16 15:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('buyer', 'Buyer (Looking for room)'), ('tenant', 'Tenant (Renting out room)')], default='buyer', max_length=10),
        ),
    ]
