# Generated by Django 6.0.4 on 2026-04-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_created_at_alter_profile_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('tenant', 'Tenant (Lister/Owner)'), ('buyer', 'Buyer (Renter)')], default='buyer', max_length=10),
        ),
    ]
